### ISSUE TITLE
Investigate problems with 0.3.1 release.

### ISSUE THREAD

**Issue by GoldenBadger** [CPSSD/heracles#332]
<a href="https://github.com/VoyTechnology"><img src="https://avatars2.githubusercontent.com/u/9013382?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [VoyTechnology](https://github.com/VoyTechnology)**
_Friday Jan 19, 2018 at 13:13 GMT_
_Originally opened as https://github.com/CPSSD/cerberus/issues/332_

----

The system does not seem to work on v0.3.1. We should trace back through commits trying to identify the blocking bugs and produce a postmortem.

Please report any findings on this thread and link to this page in any PRs which relate to this fix.

**Comment by VoyTechnology** [comment]
Release v0.3.1 is not present in Heracles. The whole architecture has also changed, so this issue is stale.
